name: loan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  # expendable_fab: ^0.0.3
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  fluttertoast: ^8.0.9
  get: 4.6.5
  get_storage: ^2.0.3
  liquid_swipe: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: QKS
      fonts:
        - asset: assets/fonts/Arima-Thin.ttf
          weight: 100
        - asset: assets/fonts/Arima-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Arima-Light.ttf
          weight: 300
        - asset: assets/fonts/Arima-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arima-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arima-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arima-Bold.ttf
          weight: 700

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  #color: "#e1f5fe"
  background_image: "assets/splash.png"
  android_12:
    ? image #assets/android12splash.png
  fullscreen: true
